### PR TITLE
Support traits

### PR DESCRIPTION
**Pull request by ennru**
* strip `interface` to support traits and interfaces
* support Boolean in config
* workaround for erased base types within Options
* possibility to switch off Java API generation

### CODE REVIEW

**Review by 2m — APPROVED** [review]
LGTM

**Comment by 2m** [comment]
Do not have the proper rights to merge this.

**Comment by ktoso** [comment]
You need to confirm the invite https://github.com/ktoso/kaze-class/invitations

**Comment by 2m** [comment]
Ooh. Missed an email for that. Thanks!

**Pull request merged**
